export default {
    SET_STATUSBAR_DATA: "SET_STATUSBAR_DATA",
    SET_R1_DATA: "SET_R1_DATA",
    SET_R2_DATA: "SET_R2_DATA",
    SET_R3_DATA: "SET_R3_DATA",
    SET_B1_DATA: "SET_B1_DATA",
    SET_B2_DATA: "SET_B2_DATA",
    SET_B3_DATA: "SET_B3_DATA",
    SET_MATCHES: "SET_MATCHES",
};
